# Dockerfile for nvidia docker with cuda11.0 with cudnn8
#
# To build: run build.sh
# To run:  docker run --rm -it -u $(id -u):$(id -g) --gpus '"device=0,1"' kamitanilab/cuda11.0_caffe:latest 
# 

FROM nvidia/cuda:11.0.3-cudnn8-devel-ubuntu20.04

ENV USER_NAME=user
ENV DEBIAN_FRONTEND=noninteractive

# install basic packages
RUN \
    apt update && \
    apt install -y tzdata && \
    apt install -y vim git sudo

# install python3
RUN apt install -y python3 python3-dev python3-pip

# install packages for caffe
RUN apt install -y zip
RUN apt install -y libopenblas-dev
RUN apt install -y cmake 
RUN apt install -y cmake-curses-gui
RUN apt install -y libboost1.71-all-dev
RUN apt install -y libleveldb-dev libprotobuf-dev
RUN apt install -y protobuf-compiler
RUN apt install -y libhdf5-dev
RUN apt install -y liblmdb-dev liblmdb++-dev
RUN apt install -y libsnappy-dev
RUN apt install -y libopencv-dev
RUN apt install -y libgoogle-glog-dev


# install other python modules
RUN pip3 install numpy scipy scikit-learn scikit-image google-api-core lmdb

# Copy caffe built on docker
COPY caffe-1.0_docker_cuda11.0.3-cudnn8-devel-ubuntu20.04  /caffe/caffe-1.0

# set path to default caffe
RUN echo "# set path to default caffe" >> /etc/bash.bashrc
RUN echo "export PYTHONPATH=/caffe/caffe-1.0/python" >> /etc/bash.bashrc


# setup user 
RUN echo "${USER_NAME} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/${USER_NAME}
RUN chmod u+s /usr/sbin/useradd && chmod u+s /usr/sbin/groupadd 

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]
